image: java:8-jdk

stages:
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - ./gradlew setupCIWorkspace
    - ./gradlew build
  artifacts:
    paths:
      - output/*.jar
    expire_in: 1 week
  only:
    - master

deploy:
  stage: deploy
  script:
    - ./deploy
    
after_script:
  - echo "End CI"