name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
    - name: Push Successful build to Discord
      if: success()
      env:
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        chmod +x discord.sh
        ./discord.sh success $WEBHOOK_URL
    - name: Push Failure to Discord
      if: failure()
      env:
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
       chmod +x discord.sh
       ./discord.sh failure $WEBHOOK_URL
